#ifndef _WEBGBA_EMULATOR_CPU_ARM7TDMI_INSTRUCTIONS_ADDRESS_MODE_
#define _WEBGBA_EMULATOR_CPU_ARM7TDMI_INSTRUCTIONS_ADDRESS_MODE_

typedef enum {
  ADDRESS_MODE_DECREMENT_AFTER,
  ADDRESS_MODE_DECREMENT_BEFORE,
  ADDRESS_MODE_INCREMENT_AFTER,
  ADDRESS_MODE_INCREMENT_BEFORE,
} ArmAddressMode;

#endif  // _WEBGBA_EMULATOR_CPU_ARM7TDMI_INSTRUCTIONS_ADDRESS_MODE_