#ifndef _WEBGBA_EMULATOR_CPU_ARM7TDMI_INSTRUCTIONS_COPROCESSOR_DATA_OPERATION_
#define _WEBGBA_EMULATOR_CPU_ARM7TDMI_INSTRUCTIONS_COPROCESSOR_DATA_OPERATION_

#include "emulator/cpu/arm7tdmi/exceptions.h"

static inline void ArmCDP(ArmAllRegisters *registers) {
  ArmExceptionUND(registers);
}

#endif  // _WEBGBA_EMULATOR_CPU_ARM7TDMI_INSTRUCTIONS_COPROCESSOR_DATA_OPERATION_