load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//emulator/cpu/arm7tdmi/decoders/arm:__subpackages__"])

cc_binary(
    name = "arm_opcode_table",
    srcs = ["arm_opcode_table.cc"],
)