load("@rules_cc//cc:defs.bzl", "cc_binary")

# package(default_visibility = ["//emulator/cpu/arm7tdmi/decoders/thumb:__subpackages__"])

cc_binary(
    name = "thumb_opcode_table",
    srcs = ["thumb_opcode_table.cc"],
)