#ifndef _WEBGBA_EMULATOR_PPU_GBA_PPU_OPENGL_TEXTURE_BINDINGS_
#define _WEBGBA_EMULATOR_PPU_GBA_PPU_OPENGL_TEXTURE_BINDINGS_

// Control
#define BACKGROUNDS_TEXTURE 0u

// Effects
#define WINDOW_TEXTURE 1u
#define BLEND_TEXTURE 2u

// Objects
#define OBJECT_TRANSFORMATIONS_TEXTURE 3u
#define OBJECT_ATTRIBUTES_TEXTURE 4u
#define OBJECT_ROWS_TEXTURE 5u
#define OBJECT_COLUMNS_TEXTURE 6u
#define OBJECT_INDICES_MASKS_TEXTURE 7u

// Coordinates
#define BG_AFFINE_COORDINATES_TEXTURE 8u
#define BG_SCROLLING_COORDINATES_TEXTURE 9u

// Palettes
#define BG_PALETTE_TEXTURE 10u
#define OBJ_PALETTE_TEXTURE 11u

// Tiles
#define BG_TILES_TEXTURE 12u
#define OBJ_TILES_TEXTURE 13u

// Tilemaps
#define BG_AFFINE_TILEMAP_TEXTURE 14u
#define BG_SCROLLING_TILEMAP_TEXTURE 15u

// Bitmaps
#define BITMAP_TEXTURE 9u
#define PALETTE_BITMAP_TEXTURE 9u

#endif  // _WEBGBA_EMULATOR_PPU_GBA_PPU_OPENGL_TEXTURE_BINDINGS_