#ifndef _WEBGBA_EMULATOR_PPU_GBA_PPU_OPENGL_TEXTURE_BINDINGS_
#define _WEBGBA_EMULATOR_PPU_GBA_PPU_OPENGL_TEXTURE_BINDINGS_

// Objects
#define OBJECT_TRANSFORMATIONS_TEXTURE 1u
#define OBJECT_ATTRIBUTES_TEXTURE 2u

// Palettes
#define BG_PALETTE_TEXTURE 3u
#define OBJ_PALETTE_TEXTURE 4u

// Tiles
#define BG_TILES_TEXTURE 5u
#define OBJ_TILES_TEXTURE 6u

// Tilemaps
#define BG_AFFINE_TILEMAP_TEXTURE 7u
#define BG_SCROLLING_TILEMAP_TEXTURE 8u

// Bitmaps
#define BITMAP_TEXTURE 9u
#define PALETTE_BITMAP_TEXTURE 10u

#endif  // _WEBGBA_EMULATOR_PPU_GBA_PPU_OPENGL_TEXTURE_BINDINGS_