#ifndef _WEBGBA_EMULATOR_PPU_GBA_PPU_OPENGL_TEXTURE_BINDINGS_
#define _WEBGBA_EMULATOR_PPU_GBA_PPU_OPENGL_TEXTURE_BINDINGS_

#define BITMAP_TEXTURE 0u
#define PALETTE_BITMAP_TEXTURE 1u
#define BG_AFFINE_TILEMAP_TEXTURE 2u
#define BG_SCROLLING_TILEMAP_TEXTURE 3u
#define BG_TILES_TEXTURE 4u
#define OBJ_TILES_TEXTURE 5u
#define OBJ_CENTER_AND_HALF_SIZE_TEXTURE 6u
#define OBJ_TRANSFORMATIONS_TEXTURE 7u
#define OBJ_VISIBILITY_TEXTURE 8u
#define BG_PALETTE_TEXTURE 9u
#define OBJ_PALETTE_TEXTURE 10u
#define BG_AFFINE_COORDINATES_TEXTURE 11u
#define WINDOW_TEXTURE 12u
#define BLEND_TEXTURE 13u
#define BACKGROUNDS_TEXTURE 14u
#define BG_SCROLLING_COORDINATES_TEXTURE 15u
#define OBJECT_TRANSFORMATIONS_TEXTURE 16u
#define OBJECT_ATTRIBUTES_TEXTURE 17u
#define OBJECT_ROWS_TEXTURE 18u
#define OBJECT_COLUMNS_TEXTURE 19u

#endif  // _WEBGBA_EMULATOR_PPU_GBA_PPU_OPENGL_TEXTURE_BINDINGS_