load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:private"])

cc_library(
    name = "cpu",
    hdrs = ["cpu.h"],
    srcs = ["cpu.c"],
    visibility = ["//visibility:public"],
)