name: Publish to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y libgles2-mesa-dev libgoogle-perftools-dev libsdl1.2-dev

    - name: Test Emulator
      run: bazel test -c opt emulator/...

    - name: Build
      run: bazel build -c opt front_end/sdl:webgba_wasm

    - name: Prepare Output
      run: |
        cp bazel-bin/front_end/sdl/webgba_wasm/webgba.js front_end/pwa/
        cp bazel-bin/front_end/sdl/webgba_wasm/webgba.wasm front_end/pwa/
        cp third_party/totushi/magenta.png front_end/pwa/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./bazel-bin/front_end/pwa
        cname: webgba.app